#!/usr/bin/env bash
# Generated by fabricdeploy. Ensures GitHub Environments for the delivery gates,
# and prints the approver groups to set as required reviewers (GitHub required
# reviewers are GitHub users/teams — map your Entra groups to teams; see README.md).
# Prereqs: `gh` CLI logged in with repo admin; run from the repo.
set -euo pipefail
REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner)"

ensure_env () {  # $1 = environment name
  echo "Ensuring environment: $1 (repo=$REPO)"
  gh api -X PUT "repos/$REPO/environments/$1" >/dev/null
}

echo "GATE fabricdeploy-change-approval -> required reviewers: 11111-11111-11111-11111"
ensure_env "fabricdeploy-change-approval"
ensure_env "fabricdeploy-nonprod"
echo "GATE fabricdeploy-nonprod -> auto-deploy DISABLED: set required reviewers"
ensure_env "fabricdeploy-prod"
echo "GATE fabricdeploy-prod deploy -> required reviewers: (none configured — set manually)"

echo "Done. Set required reviewers on the environments marked GATE above (see README.md)."
